### ISSUE TITLE
Differing preconditions of fromCursor() vs listFromCursor()

### ISSUE THREAD

**Issue by sevenflowenol** [chalup/microorm#10]
Before calling fromCursor() and handing it a Cursor instance, you have to call cursorInstance.moveToFirst() in order to avoid a CursorIndexOutOfBoundsException.  This seems a little strange since your listFromCursor() method takes care of this itself.  Not sure if this is intended?  If so, could you update your documentation / examples to reflect this?

**Comment by chalup** [comment]
`MicroOrm.fromCursor` is intended to be used in loop which iterates over the `Cursor` - that's why it doesn't change the position. `MicroOrm.listFromCursor` on the other hand returns the `List` of mapped rows in entire `Cursor`, so it have to take care of setting position itself.

I hope this clears your doubts. I'll add more info to `fromCursor` javadocs.
